### ISSUE TITLE
cannot connect to any environment when building off of a Polygon contract.

### ISSUE THREAD

**Issue by beatbreakerz** [Crossmint/crossmint-client-sdk#121]
Hello... ok quick issue.  Been working with severall skilled JS and React devs and nothing has worked.  

Scenario: Openzeppelin contract erc721b, Verified, absolutely no issues anywhere or on any method of minting EXCEPT crossmint.
1.> Integerating into Webflow page. (i know i know)...
2.> Imported and set src as "crossmint-client-sdk-vanilla-ui 0.0.3-alpha.1 "
3.>laid scripts to have full access to the sdk in my webflow page.

Prob=>  Every method of attempting to get the <Crossmint-Pay-Button> to connect correctly has failed.  And i tested using a Solana Candy Machine, and all worked flawless.  But when the button is connecting to a Polygon contract, it will always time out to a error "500 - Internal Server Error" 

a thorough vetting of the  address being dispatched kinda reveals the problem...

"https://www.crossmint.io/checkout/mintProcess?clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx&closeOnSuccess=false&clientName=client-sdk-vanilla-ui&clientVersion=0.0.3-alpha.0&mintConfig=null&collectionTitle=cooze+killer&collectionDescription=Cooze&collectionPhoto=%3CCOLLECTION_IMAGE_URL%3E&paymentMethod=SOL"

the flaw has to be connected to the idea that "mintConfig=null"...  

now we have literally copy and pasted any combination of args to that field in the button mintConfig prop, but no matter where or what we put, it NEVER passes thru to the website when clicked.   

if i delete the argument itself from the button setup, i get a warning  "... this contract has both an Address to, and a mintAmount argument.  You are missing the mintAmount arg.  Please place in the  mintConfig prop."  so literally putting just those 2 properties in will make the error go away, but then im back to the 500 error.  So obviously the client is satisfied with the info which is saying alot, because it will kick out ANYTHING that isnt what it wanted.   But it does not transfer into the actual connection to pay.  

can reproduce this situation on demand, so if anyone has insights please help.  

{and i spent the better part of 3 days working with a crossmint dev on discord, and so far they are completely stumped too... but are actually impressed that i was able to get further along that we did together... lol}

**Comment by beatbreakerz** [comment]
and if anyone needs the client id, go for it... i made it with the intention of using just as a way to test different parameters to get this to work.... 

ClientID: eb4c0fc4-3620-4a12-a757-419e3b9f216d

ps. i also went as far as to completely rework my smart contract to simplify the mint commands to just  "to" and "mintAmount"  EXACTLY as it asked for, and removed any other functions that utilized the same calls. and still no dice.  Plus have ran every src sdk build of vanilla from 0.0.1 - 1 up to 0.0.3 a-1.

**Comment by mPaella** [comment]
Hey @beatbreakerz sorry for the late reply. If you are still experiencing issues, please reach out on discord https://crossmint.io/discord
