### ISSUE TITLE
[feature] Send client SDK name and version with all requests

### ISSUE THREAD

**Issue by alfonso-paella** [Crossmint/crossmint-client-sdk#18]
This will help troubleshoot and debug

I think typically the standard way to do this is to set the HTTP headers:
* X-Client-Version: sdk version
* X-Client-Name: client name

But we should do some research to confirm

**Comment by pgarciaegido** [comment]
Hey @alfonso-paella ,

I have a few questions about this one:

1. When we mean all requests we mean the first GET request we make to the `/api/crossmint/onboardingRequests/${clientId}/status` endpoint, but also to the following requests we do in the popup window, correct? Im not sure we can directly pass he headers using the client API `window.open`. We probably need to pass them via query params at first and find a way to do it in next(https://nextjs.org/docs/api-reference/next.config.js/headers).
2. How would I access the client name? If im not mistaken, the only source of external information to the button is the `/status` endpoint (above mentioned).

**Comment by alfonso-paella** [comment]
Re: 1

Yeah we can pass headers for the /status endpoint, and then pass the same info encoded in custom url params for the window.open. Maybe we can stop there for now, and down the line we can decide if we also need to transitively pass headers from the checkout ui to the crossbit-main backend

----------

re 2:
X-client-name should just be a hardcoded name we give the client SDK which is calling.

We can use the same names we use in npm, e.g. "client-sdk-react-ui" (and if we later have for vue, angular, android, iOS, ... we will use diff names for those)

**Comment by alfonso-paella** [comment]
I think this is done @pgarciaegido
