### ISSUE TITLE
Can't compile if I'm not on node v16: ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by alfonso-paella** [Crossmint/crossmint-client-sdk#218]
I tried compiling with LTS (18.5 at the time of writing) and I got an error like `ERR_OSSL_EVP_UNSUPPORTED`

We shoudl either:
a) Make it so node LTS works for compiling
b) Add instructions to use node v16 for compiling

**Comment by mPaella** [comment]
fixed
