### ISSUE TITLE
Vue and Lit CrossmintPaymentElement components don't remove the event listener on unmount

### ISSUE THREAD

**Issue by jhubbardsf** [Crossmint/crossmint-client-sdk#224]
The React UI package was updated to take advantage of the returned removeEventListener from the `listenToEvents` function in `crossmintUiService.ts` and `crossmintPaymentService.ts`. The Vue and Lit web components should do the same thing so that multiple events don't fire if the component is removed from the dom and readded.

**Comment by pgarciaegido** [comment]
Resolved with https://github.com/Crossmint/crossmint-client-sdk/pull/225 and released `alpha.26`

Thanks again @jhubbardsf !!
