### ISSUE TITLE
paymentMethod prop type mismatches what the docs say for the embedded ui checkout

### ISSUE THREAD

**Issue by jhubbardsf** [Crossmint/crossmint-client-sdk#227]
The documents explaining the embedded ui's props say that `paymentMethod` should be "credit-card, google-pay, or apple-pay" ([link](https://docs.crossmint.com/docs/2c-embed-checkout-inside-your-ui#explaining-the-components-props)). This would be represented by type PaymentMethodType. Currently the PaymentElement interface is written as `paymentMethod: PaymentMethod` which is `"fiat" | "ETH" | "SOL"`.

I think the prop type needs to be switched. It's also not being appended to the iframeUrl so it currently doesn't actually do anything. 

Proposed fix:
Update type and update `crossmintPaymentService` and related components to use and pass it correctly.

**Comment by pgarciaegido** [comment]
As mentioned in the PR, this is a problem with the docs, not with the code.
