### ISSUE TITLE
[Bug] Fix font

### ISSUE THREAD

**Issue by mPaella** [Crossmint/crossmint-client-sdk#23]
We are using the incorrect font, and is loading improperly. The correct font is Inter, from google fonts

**Comment by pgarciaegido** [comment]
Before closing, I would like to take a look at [this line](https://github.com/Crossmint/crossmint-client-sdk/blob/81eb2fdd2b424bc83633c528bedfd7a37878f674/packages/ui/react-ui/src/styles/index.ts#L19) to only bring the fonts that we actually need.
