### ISSUE TITLE
[Cleanup] Rename button

### ISSUE THREAD

**Issue by alfonso-paella** [Crossmint/crossmint-client-sdk#33]
From `<CrossMintButton>` to:

`<CrossmintPayButton>`

Two changes:
1. Drop the uppercase M. We changed the brand to have Crossmint be a single word
2. Add Pay. The credit card plugin is now branded as "Pay with Crossmint", and in the future we may have other components in the SDK that are unrelated to payments, so this will futureproof it

**Comment by pgarciaegido** [comment]
This can be closed now. It was released on v0.1.0
