### ISSUE TITLE
[optimization] Do not fetch onboarding request status in the button, unless the button is configured to hideMintOnInactiveClient

### ISSUE THREAD

**Issue by alfonso-paella** [Crossmint/crossmint-client-sdk#40]
Currently, we make a network request every time a user visits a drop with crossmint

This is because we check the status of the onboarding request

However, we only need to check this status in two cases:
1. If the user is in an admin panel, using the CrossmintStatus button 
2. If the user is in a drop like holaplex where the button shouldn't show if the drop is not approved. This requires setting the dont show if invalid flag in the button (I don't remember the exact name, look into it)

**Comment by alfonso-paella** [comment]
@pgarciaegido thoughts on dealing with this one? It pollutes our logs badly

**Comment by pgarciaegido** [comment]
Yep, it makes sense! Will implement shortly
