### ISSUE TITLE
[bug] Documentation and example in gh_pages are broken

### ISSUE THREAD

**Issue by alfonso-paella** [Crossmint/crossmint-client-sdk#59]
https://crossmint.github.io/crossmint-client-sdk/ -- the title says undefined

~~https://crossmint.github.io/crossmint-client-sdk/example/ -- this 404 but it used to work~~ This works now, we just had to wait

I generated them by running:
```
yarn
yarn build # this now builds all projects and subprojects
yarn deploy
```

**Comment by alfonso-paella** [comment]
![image](https://user-images.githubusercontent.com/93743232/156034721-e73149d5-3e08-459b-bab5-1d34c8f9207a.png)

For the "example" missing issue, it may be that yarn deploy is not detecting for some reason the compiled package

**Comment by pgarciaegido** [comment]
I have deployed both myself, and they seem to be working. Could you retry again @alfonso-paella ?
![Screenshot 2022-02-28 at 20 47 02](https://user-images.githubusercontent.com/20989060/156048687-9d9e0519-c15f-45a8-98e7-5ec33fb2a798.png)
![Screenshot 2022-02-28 at 20 47 21](https://user-images.githubusercontent.com/20989060/156048745-2e26ae32-1faf-4fc1-af30-8d365e073a03.png)

**Comment by alfonso-paella** [comment]
hmm it does work now
