### ISSUE TITLE
Proposed changes

### ISSUE THREAD

**Issue by alfonso-paella** [CrossMint/crossmint-client-sdk#6]
* Remove al OG tags referencing "crossmint" on the [example](https://github.com/CrossMint/crossmint-client-sdk/blob/358bee40dee1bfa54abf61050860d152947e32c5/packages/starter/example/pages/_app.tsx)
* Remove the candy machine ID from the [example](https://github.com/CrossMint/crossmint-client-sdk/blob/358bee40dee1bfa54abf61050860d152947e32c5/packages/starter/example/pages/index.tsx), and put a placeholder instead

**Comment by alfonso-paella** [comment]
@mPaella I took a look at your changes from yesterday. What do you think of those two suggestions?

**Comment by mPaella** [comment]
The example project is essentially a clone of the nextjs one, the purpose of it is to be a hosted example of the full flow.

So removing this stuff defeats the purpose of having the example in the first place.

**Comment by alfonso-paella** [comment]
I see. I had misunderstood that. 

I think we may see people screw this up, but not sure. Resolving for now and we can revisit this if indeed we see ppl getting it wrong
